# Generated by Django 2.1.7 on 2019-03-08 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exams.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(choices=[(2017, '2017-2018'), (2018, '2018-2019'), (2019, '2019-2020')])),
                ('semester', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer School')], max_length=6)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='AssistantAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Assistant')),
            ],
        ),
        migrations.CreateModel(
            name='AssistedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Assistant')),
            ],
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1)),
                ('row', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)])),
                ('assign_order', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, unique=True)),
                ('soft_capacity', models.PositiveSmallIntegerField(default=0)),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
                ('block', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(default=None, max_length=100)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name_en', models.CharField(max_length=50)),
                ('name_tr', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.Chair')),
            ],
        ),
        migrations.CreateModel(
            name='NoExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.AcademicYear')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Department')),
                ('instructor_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_in_charge', to='exams.Instructor')),
                ('instructors', models.ManyToManyField(to='exams.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('midterm', 'Midterm'), ('makeup', 'Make-up'), ('final', 'Final'), ('resit', 'Resit')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.AcademicYear')),
            ],
        ),
        migrations.CreateModel(
            name='Sitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistants', models.ManyToManyField(through='exams.AssistantAssignment', to='exams.Assistant')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Classroom')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tckn', models.BigIntegerField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.PositiveSmallIntegerField()),
                ('long_code', models.PositiveSmallIntegerField()),
                ('time', models.DateTimeField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Period')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam', validators=[exams.validators.validate_noexam])),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.TimeCode')),
            ],
        ),
        migrations.AddField(
            model_name='noexam',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Period'),
        ),
        migrations.AddField(
            model_name='layout',
            name='sitting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Sitting'),
        ),
        migrations.AddField(
            model_name='layout',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Offering'),
        ),
        migrations.AddField(
            model_name='exam',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Period'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Student'),
        ),
        migrations.AddField(
            model_name='chair',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Classroom'),
        ),
        migrations.AddField(
            model_name='assistedcourse',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Offering'),
        ),
        migrations.AddField(
            model_name='assistantassignment',
            name='sitting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Sitting'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Department'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('year', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='timecode',
            unique_together={('time', 'period'), ('short_code', 'period'), ('long_code', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='sitting',
            unique_together={('exam', 'classroom')},
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('academic_year', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='offering',
            unique_together={('course', 'department', 'section', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='noexam',
            unique_together={('course', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='layout',
            unique_together={('sitting', 'chair'), ('student', 'sitting')},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('offering', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'exam')},
        ),
        migrations.AlterUniqueTogether(
            name='chair',
            unique_together={('classroom', 'column', 'row'), ('classroom', 'assign_order')},
        ),
    ]
