# Generated by Django 2.1.7 on 2019-03-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecode',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
